### ISSUE TITLE
Not working gives an error

### ISSUE THREAD

**Issue by SnchitGrover** [awran5/react-material-ui-step-form#1]
Hi,

First of all.. Thanks a lot for this example..

But when I cloned your repository, it didn't work.. 
Downloading source code from https://codesandbox.io/s/react-material-ui-step-form-ui788 seems to have worked the issue.

If was giving some error related to PATH..

**Comment by awran5** [comment]
Sorry for the late reply. I'm closing this issue due inactivity. Please let me know if you have any issue.
