### ISSUE TITLE
Handling File Input

### ISSUE THREAD

**Issue by I-am-abdulazeez** [awran5/react-material-ui-step-form#3]
Thanks for this sir. 

The `handleChange` cannot fire the form target, so when i select a file and try to go back, it cannot retain the state of the form and it throws error:

`Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.`

```
<TextField
            fullWidth
            variant="outlined"
            size="small"
            type="file"
            name="memoradum_ArticlesOfAssociation"
            label="Memoradum Articles Of Association"
            value={memoradum_ArticlesOfAssociation || ""}
            onChange={(e) => {
              // handleFormHere
            }}
            required
          /> 
```

**Comment by awran5** [comment]
I'm sorry for the late replay but Material UI still doesn't support `file` input
